name: 03 - Workflows Runner

on: push

jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show OS
              run: |
                echo "This job runs under Ubuntu runner"
                echo "Runner OS: $RUNNER_OS -- $(uname -s) $(uname -r)"